### ISSUE TITLE
代码import报错

### ISSUE THREAD

**Issue by huangwentao123** [MingjieWang0606/FedCL_Pubic#3]
`Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from FLAlgorithms.servers.serverpFedGen import FedGen
  File "C:\Users\admin\Desktop\git\FedCL_Pubic\FLAlgorithms\servers\serverpFedGen.py", line 1, in <module>
    from FLAlgorithms.users.userpFedGen import UserpFedGen
  File "C:\Users\admin\Desktop\git\FedCL_Pubic\FLAlgorithms\users\userpFedGen.py", line 8, in <module>
    from utils.model_utils import get_dataset_name, CONFIGS
ImportError: cannot import name 'CONFIGS'`

**Comment by MingjieWang0606** [comment]
Ummm 检查你自己的运行路径
目前代码是可以直接运行的
